import type { Metadata } from "next";
import {Urbanist} from "next/font/google";
import React from "react";
import Sidebar from "@/components/sidebar";
import {DashboardTabProvider} from "@/context/dashboardTabContext";


const urbanist = Urbanist({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body
            className={urbanist.className}
        >
            <DashboardTabProvider>
                <div className="row" style={{width:'100%'}}>
                    <Sidebar />
                    <div className={'col'}>
                        <div style={{display: "flex", padding: '20px 40px', justifyContent: 'space-between',marginBottom:'24px' }}>
                            <span className={'welcome'}>Bienvenue, Andri A.</span>
                            <div style={{display:"flex",width:"fit-content",alignItems:"center",gap:"10px"}}>
                                <button className={'button'}><img src="/icons/gong.svg" alt=""/></button>
                                <img src="/pictures/Avatar.png" alt="" style={{width:'50px', height:'50px'}} />
                            </div>
                        </div>
                        <div>{children}</div>
                    </div>
                </div>
            </DashboardTabProvider>
        </body>
        </html>
    );
}